name: CI

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run Ruff
        uses: astral-sh/ruff-action@v3
      
      - name: Run Ty
        run: uv run ty check .

      - name: Run Pytest
        run: uv run pytest tests -v --cov --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Run pdoc
        run: uv run pdoc -o ./docs sparsediffax --docformat google
        env:
          PDOC_ALLOW_EXEC: 1

      - name: Upload HTML docs as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/

  # Deploy the artifact to GitHub pages.
  # This is a separate job so that only actions/deploy-pages has the necessary permissions.
  deploy:
    needs: run
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4